language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t josecho/docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true josecho/docker-test npm test -- --coverage

after_success:
  - docker build -t josecho/multi-client ./client
  - docker build -t josecho/multi-nginx ./nginx
  - docker build -t josecho/multi-server ./server
  - docker build -t josecho/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push josecho/multi-client
  - docker push josecho/multi-nginx
  - docker push josecho/multi-server
  - docker push josecho/multi-worker
